
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Translation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Translation
 * 
 */
export type TranslationModel = runtime.Types.Result.DefaultSelection<Prisma.$TranslationPayload>

export type AggregateTranslation = {
  _count: TranslationCountAggregateOutputType | null
  _avg: TranslationAvgAggregateOutputType | null
  _sum: TranslationSumAggregateOutputType | null
  _min: TranslationMinAggregateOutputType | null
  _max: TranslationMaxAggregateOutputType | null
}

export type TranslationAvgAggregateOutputType = {
  progress: number | null
  retryCount: number | null
}

export type TranslationSumAggregateOutputType = {
  progress: number | null
  retryCount: number | null
}

export type TranslationMinAggregateOutputType = {
  id: string | null
  videoId: string | null
  targetLanguage: string | null
  status: $Enums.TranslationStatus | null
  currentStep: $Enums.PipelineStep | null
  progress: number | null
  extractedAudioKey: string | null
  synthesizedAudioKey: string | null
  resultVideoKey: string | null
  fishAudioVoiceId: string | null
  errorMessage: string | null
  errorStep: $Enums.PipelineStep | null
  retryCount: number | null
  startedAt: Date | null
  completedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TranslationMaxAggregateOutputType = {
  id: string | null
  videoId: string | null
  targetLanguage: string | null
  status: $Enums.TranslationStatus | null
  currentStep: $Enums.PipelineStep | null
  progress: number | null
  extractedAudioKey: string | null
  synthesizedAudioKey: string | null
  resultVideoKey: string | null
  fishAudioVoiceId: string | null
  errorMessage: string | null
  errorStep: $Enums.PipelineStep | null
  retryCount: number | null
  startedAt: Date | null
  completedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TranslationCountAggregateOutputType = {
  id: number
  videoId: number
  targetLanguage: number
  status: number
  currentStep: number
  progress: number
  extractedAudioKey: number
  transcriptJson: number
  translatedJson: number
  synthesizedAudioKey: number
  resultVideoKey: number
  fishAudioVoiceId: number
  fishAudioVoiceMap: number
  errorMessage: number
  errorStep: number
  retryCount: number
  startedAt: number
  completedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TranslationAvgAggregateInputType = {
  progress?: true
  retryCount?: true
}

export type TranslationSumAggregateInputType = {
  progress?: true
  retryCount?: true
}

export type TranslationMinAggregateInputType = {
  id?: true
  videoId?: true
  targetLanguage?: true
  status?: true
  currentStep?: true
  progress?: true
  extractedAudioKey?: true
  synthesizedAudioKey?: true
  resultVideoKey?: true
  fishAudioVoiceId?: true
  errorMessage?: true
  errorStep?: true
  retryCount?: true
  startedAt?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type TranslationMaxAggregateInputType = {
  id?: true
  videoId?: true
  targetLanguage?: true
  status?: true
  currentStep?: true
  progress?: true
  extractedAudioKey?: true
  synthesizedAudioKey?: true
  resultVideoKey?: true
  fishAudioVoiceId?: true
  errorMessage?: true
  errorStep?: true
  retryCount?: true
  startedAt?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type TranslationCountAggregateInputType = {
  id?: true
  videoId?: true
  targetLanguage?: true
  status?: true
  currentStep?: true
  progress?: true
  extractedAudioKey?: true
  transcriptJson?: true
  translatedJson?: true
  synthesizedAudioKey?: true
  resultVideoKey?: true
  fishAudioVoiceId?: true
  fishAudioVoiceMap?: true
  errorMessage?: true
  errorStep?: true
  retryCount?: true
  startedAt?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TranslationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Translation to aggregate.
   */
  where?: Prisma.TranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Translations to fetch.
   */
  orderBy?: Prisma.TranslationOrderByWithRelationInput | Prisma.TranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Translations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Translations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Translations
  **/
  _count?: true | TranslationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TranslationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TranslationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TranslationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TranslationMaxAggregateInputType
}

export type GetTranslationAggregateType<T extends TranslationAggregateArgs> = {
      [P in keyof T & keyof AggregateTranslation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTranslation[P]>
    : Prisma.GetScalarType<T[P], AggregateTranslation[P]>
}




export type TranslationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TranslationWhereInput
  orderBy?: Prisma.TranslationOrderByWithAggregationInput | Prisma.TranslationOrderByWithAggregationInput[]
  by: Prisma.TranslationScalarFieldEnum[] | Prisma.TranslationScalarFieldEnum
  having?: Prisma.TranslationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TranslationCountAggregateInputType | true
  _avg?: TranslationAvgAggregateInputType
  _sum?: TranslationSumAggregateInputType
  _min?: TranslationMinAggregateInputType
  _max?: TranslationMaxAggregateInputType
}

export type TranslationGroupByOutputType = {
  id: string
  videoId: string
  targetLanguage: string
  status: $Enums.TranslationStatus
  currentStep: $Enums.PipelineStep | null
  progress: number
  extractedAudioKey: string | null
  transcriptJson: runtime.JsonValue | null
  translatedJson: runtime.JsonValue | null
  synthesizedAudioKey: string | null
  resultVideoKey: string | null
  fishAudioVoiceId: string | null
  fishAudioVoiceMap: runtime.JsonValue | null
  errorMessage: string | null
  errorStep: $Enums.PipelineStep | null
  retryCount: number
  startedAt: Date | null
  completedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: TranslationCountAggregateOutputType | null
  _avg: TranslationAvgAggregateOutputType | null
  _sum: TranslationSumAggregateOutputType | null
  _min: TranslationMinAggregateOutputType | null
  _max: TranslationMaxAggregateOutputType | null
}

type GetTranslationGroupByPayload<T extends TranslationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TranslationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TranslationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TranslationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TranslationGroupByOutputType[P]>
      }
    >
  >



export type TranslationWhereInput = {
  AND?: Prisma.TranslationWhereInput | Prisma.TranslationWhereInput[]
  OR?: Prisma.TranslationWhereInput[]
  NOT?: Prisma.TranslationWhereInput | Prisma.TranslationWhereInput[]
  id?: Prisma.StringFilter<"Translation"> | string
  videoId?: Prisma.StringFilter<"Translation"> | string
  targetLanguage?: Prisma.StringFilter<"Translation"> | string
  status?: Prisma.EnumTranslationStatusFilter<"Translation"> | $Enums.TranslationStatus
  currentStep?: Prisma.EnumPipelineStepNullableFilter<"Translation"> | $Enums.PipelineStep | null
  progress?: Prisma.IntFilter<"Translation"> | number
  extractedAudioKey?: Prisma.StringNullableFilter<"Translation"> | string | null
  transcriptJson?: Prisma.JsonNullableFilter<"Translation">
  translatedJson?: Prisma.JsonNullableFilter<"Translation">
  synthesizedAudioKey?: Prisma.StringNullableFilter<"Translation"> | string | null
  resultVideoKey?: Prisma.StringNullableFilter<"Translation"> | string | null
  fishAudioVoiceId?: Prisma.StringNullableFilter<"Translation"> | string | null
  fishAudioVoiceMap?: Prisma.JsonNullableFilter<"Translation">
  errorMessage?: Prisma.StringNullableFilter<"Translation"> | string | null
  errorStep?: Prisma.EnumPipelineStepNullableFilter<"Translation"> | $Enums.PipelineStep | null
  retryCount?: Prisma.IntFilter<"Translation"> | number
  startedAt?: Prisma.DateTimeNullableFilter<"Translation"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableFilter<"Translation"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Translation"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Translation"> | Date | string
  video?: Prisma.XOR<Prisma.VideoScalarRelationFilter, Prisma.VideoWhereInput>
}

export type TranslationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  status?: Prisma.SortOrder
  currentStep?: Prisma.SortOrderInput | Prisma.SortOrder
  progress?: Prisma.SortOrder
  extractedAudioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  transcriptJson?: Prisma.SortOrderInput | Prisma.SortOrder
  translatedJson?: Prisma.SortOrderInput | Prisma.SortOrder
  synthesizedAudioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  resultVideoKey?: Prisma.SortOrderInput | Prisma.SortOrder
  fishAudioVoiceId?: Prisma.SortOrderInput | Prisma.SortOrder
  fishAudioVoiceMap?: Prisma.SortOrderInput | Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  errorStep?: Prisma.SortOrderInput | Prisma.SortOrder
  retryCount?: Prisma.SortOrder
  startedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  video?: Prisma.VideoOrderByWithRelationInput
}

export type TranslationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TranslationWhereInput | Prisma.TranslationWhereInput[]
  OR?: Prisma.TranslationWhereInput[]
  NOT?: Prisma.TranslationWhereInput | Prisma.TranslationWhereInput[]
  videoId?: Prisma.StringFilter<"Translation"> | string
  targetLanguage?: Prisma.StringFilter<"Translation"> | string
  status?: Prisma.EnumTranslationStatusFilter<"Translation"> | $Enums.TranslationStatus
  currentStep?: Prisma.EnumPipelineStepNullableFilter<"Translation"> | $Enums.PipelineStep | null
  progress?: Prisma.IntFilter<"Translation"> | number
  extractedAudioKey?: Prisma.StringNullableFilter<"Translation"> | string | null
  transcriptJson?: Prisma.JsonNullableFilter<"Translation">
  translatedJson?: Prisma.JsonNullableFilter<"Translation">
  synthesizedAudioKey?: Prisma.StringNullableFilter<"Translation"> | string | null
  resultVideoKey?: Prisma.StringNullableFilter<"Translation"> | string | null
  fishAudioVoiceId?: Prisma.StringNullableFilter<"Translation"> | string | null
  fishAudioVoiceMap?: Prisma.JsonNullableFilter<"Translation">
  errorMessage?: Prisma.StringNullableFilter<"Translation"> | string | null
  errorStep?: Prisma.EnumPipelineStepNullableFilter<"Translation"> | $Enums.PipelineStep | null
  retryCount?: Prisma.IntFilter<"Translation"> | number
  startedAt?: Prisma.DateTimeNullableFilter<"Translation"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableFilter<"Translation"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Translation"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Translation"> | Date | string
  video?: Prisma.XOR<Prisma.VideoScalarRelationFilter, Prisma.VideoWhereInput>
}, "id">

export type TranslationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  status?: Prisma.SortOrder
  currentStep?: Prisma.SortOrderInput | Prisma.SortOrder
  progress?: Prisma.SortOrder
  extractedAudioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  transcriptJson?: Prisma.SortOrderInput | Prisma.SortOrder
  translatedJson?: Prisma.SortOrderInput | Prisma.SortOrder
  synthesizedAudioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  resultVideoKey?: Prisma.SortOrderInput | Prisma.SortOrder
  fishAudioVoiceId?: Prisma.SortOrderInput | Prisma.SortOrder
  fishAudioVoiceMap?: Prisma.SortOrderInput | Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  errorStep?: Prisma.SortOrderInput | Prisma.SortOrder
  retryCount?: Prisma.SortOrder
  startedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TranslationCountOrderByAggregateInput
  _avg?: Prisma.TranslationAvgOrderByAggregateInput
  _max?: Prisma.TranslationMaxOrderByAggregateInput
  _min?: Prisma.TranslationMinOrderByAggregateInput
  _sum?: Prisma.TranslationSumOrderByAggregateInput
}

export type TranslationScalarWhereWithAggregatesInput = {
  AND?: Prisma.TranslationScalarWhereWithAggregatesInput | Prisma.TranslationScalarWhereWithAggregatesInput[]
  OR?: Prisma.TranslationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TranslationScalarWhereWithAggregatesInput | Prisma.TranslationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Translation"> | string
  videoId?: Prisma.StringWithAggregatesFilter<"Translation"> | string
  targetLanguage?: Prisma.StringWithAggregatesFilter<"Translation"> | string
  status?: Prisma.EnumTranslationStatusWithAggregatesFilter<"Translation"> | $Enums.TranslationStatus
  currentStep?: Prisma.EnumPipelineStepNullableWithAggregatesFilter<"Translation"> | $Enums.PipelineStep | null
  progress?: Prisma.IntWithAggregatesFilter<"Translation"> | number
  extractedAudioKey?: Prisma.StringNullableWithAggregatesFilter<"Translation"> | string | null
  transcriptJson?: Prisma.JsonNullableWithAggregatesFilter<"Translation">
  translatedJson?: Prisma.JsonNullableWithAggregatesFilter<"Translation">
  synthesizedAudioKey?: Prisma.StringNullableWithAggregatesFilter<"Translation"> | string | null
  resultVideoKey?: Prisma.StringNullableWithAggregatesFilter<"Translation"> | string | null
  fishAudioVoiceId?: Prisma.StringNullableWithAggregatesFilter<"Translation"> | string | null
  fishAudioVoiceMap?: Prisma.JsonNullableWithAggregatesFilter<"Translation">
  errorMessage?: Prisma.StringNullableWithAggregatesFilter<"Translation"> | string | null
  errorStep?: Prisma.EnumPipelineStepNullableWithAggregatesFilter<"Translation"> | $Enums.PipelineStep | null
  retryCount?: Prisma.IntWithAggregatesFilter<"Translation"> | number
  startedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Translation"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Translation"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Translation"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Translation"> | Date | string
}

export type TranslationCreateInput = {
  id?: string
  targetLanguage: string
  status?: $Enums.TranslationStatus
  currentStep?: $Enums.PipelineStep | null
  progress?: number
  extractedAudioKey?: string | null
  transcriptJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  synthesizedAudioKey?: string | null
  resultVideoKey?: string | null
  fishAudioVoiceId?: string | null
  fishAudioVoiceMap?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  errorMessage?: string | null
  errorStep?: $Enums.PipelineStep | null
  retryCount?: number
  startedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  video: Prisma.VideoCreateNestedOneWithoutTranslationsInput
}

export type TranslationUncheckedCreateInput = {
  id?: string
  videoId: string
  targetLanguage: string
  status?: $Enums.TranslationStatus
  currentStep?: $Enums.PipelineStep | null
  progress?: number
  extractedAudioKey?: string | null
  transcriptJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  synthesizedAudioKey?: string | null
  resultVideoKey?: string | null
  fishAudioVoiceId?: string | null
  fishAudioVoiceMap?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  errorMessage?: string | null
  errorStep?: $Enums.PipelineStep | null
  retryCount?: number
  startedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTranslationStatusFieldUpdateOperationsInput | $Enums.TranslationStatus
  currentStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  extractedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transcriptJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  synthesizedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resultVideoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceMap?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  retryCount?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  video?: Prisma.VideoUpdateOneRequiredWithoutTranslationsNestedInput
}

export type TranslationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTranslationStatusFieldUpdateOperationsInput | $Enums.TranslationStatus
  currentStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  extractedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transcriptJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  synthesizedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resultVideoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceMap?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  retryCount?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationCreateManyInput = {
  id?: string
  videoId: string
  targetLanguage: string
  status?: $Enums.TranslationStatus
  currentStep?: $Enums.PipelineStep | null
  progress?: number
  extractedAudioKey?: string | null
  transcriptJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  synthesizedAudioKey?: string | null
  resultVideoKey?: string | null
  fishAudioVoiceId?: string | null
  fishAudioVoiceMap?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  errorMessage?: string | null
  errorStep?: $Enums.PipelineStep | null
  retryCount?: number
  startedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTranslationStatusFieldUpdateOperationsInput | $Enums.TranslationStatus
  currentStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  extractedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transcriptJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  synthesizedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resultVideoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceMap?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  retryCount?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTranslationStatusFieldUpdateOperationsInput | $Enums.TranslationStatus
  currentStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  extractedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transcriptJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  synthesizedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resultVideoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceMap?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  retryCount?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationListRelationFilter = {
  every?: Prisma.TranslationWhereInput
  some?: Prisma.TranslationWhereInput
  none?: Prisma.TranslationWhereInput
}

export type TranslationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TranslationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  status?: Prisma.SortOrder
  currentStep?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  extractedAudioKey?: Prisma.SortOrder
  transcriptJson?: Prisma.SortOrder
  translatedJson?: Prisma.SortOrder
  synthesizedAudioKey?: Prisma.SortOrder
  resultVideoKey?: Prisma.SortOrder
  fishAudioVoiceId?: Prisma.SortOrder
  fishAudioVoiceMap?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  errorStep?: Prisma.SortOrder
  retryCount?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TranslationAvgOrderByAggregateInput = {
  progress?: Prisma.SortOrder
  retryCount?: Prisma.SortOrder
}

export type TranslationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  status?: Prisma.SortOrder
  currentStep?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  extractedAudioKey?: Prisma.SortOrder
  synthesizedAudioKey?: Prisma.SortOrder
  resultVideoKey?: Prisma.SortOrder
  fishAudioVoiceId?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  errorStep?: Prisma.SortOrder
  retryCount?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TranslationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  status?: Prisma.SortOrder
  currentStep?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  extractedAudioKey?: Prisma.SortOrder
  synthesizedAudioKey?: Prisma.SortOrder
  resultVideoKey?: Prisma.SortOrder
  fishAudioVoiceId?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  errorStep?: Prisma.SortOrder
  retryCount?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TranslationSumOrderByAggregateInput = {
  progress?: Prisma.SortOrder
  retryCount?: Prisma.SortOrder
}

export type TranslationCreateNestedManyWithoutVideoInput = {
  create?: Prisma.XOR<Prisma.TranslationCreateWithoutVideoInput, Prisma.TranslationUncheckedCreateWithoutVideoInput> | Prisma.TranslationCreateWithoutVideoInput[] | Prisma.TranslationUncheckedCreateWithoutVideoInput[]
  connectOrCreate?: Prisma.TranslationCreateOrConnectWithoutVideoInput | Prisma.TranslationCreateOrConnectWithoutVideoInput[]
  createMany?: Prisma.TranslationCreateManyVideoInputEnvelope
  connect?: Prisma.TranslationWhereUniqueInput | Prisma.TranslationWhereUniqueInput[]
}

export type TranslationUncheckedCreateNestedManyWithoutVideoInput = {
  create?: Prisma.XOR<Prisma.TranslationCreateWithoutVideoInput, Prisma.TranslationUncheckedCreateWithoutVideoInput> | Prisma.TranslationCreateWithoutVideoInput[] | Prisma.TranslationUncheckedCreateWithoutVideoInput[]
  connectOrCreate?: Prisma.TranslationCreateOrConnectWithoutVideoInput | Prisma.TranslationCreateOrConnectWithoutVideoInput[]
  createMany?: Prisma.TranslationCreateManyVideoInputEnvelope
  connect?: Prisma.TranslationWhereUniqueInput | Prisma.TranslationWhereUniqueInput[]
}

export type TranslationUpdateManyWithoutVideoNestedInput = {
  create?: Prisma.XOR<Prisma.TranslationCreateWithoutVideoInput, Prisma.TranslationUncheckedCreateWithoutVideoInput> | Prisma.TranslationCreateWithoutVideoInput[] | Prisma.TranslationUncheckedCreateWithoutVideoInput[]
  connectOrCreate?: Prisma.TranslationCreateOrConnectWithoutVideoInput | Prisma.TranslationCreateOrConnectWithoutVideoInput[]
  upsert?: Prisma.TranslationUpsertWithWhereUniqueWithoutVideoInput | Prisma.TranslationUpsertWithWhereUniqueWithoutVideoInput[]
  createMany?: Prisma.TranslationCreateManyVideoInputEnvelope
  set?: Prisma.TranslationWhereUniqueInput | Prisma.TranslationWhereUniqueInput[]
  disconnect?: Prisma.TranslationWhereUniqueInput | Prisma.TranslationWhereUniqueInput[]
  delete?: Prisma.TranslationWhereUniqueInput | Prisma.TranslationWhereUniqueInput[]
  connect?: Prisma.TranslationWhereUniqueInput | Prisma.TranslationWhereUniqueInput[]
  update?: Prisma.TranslationUpdateWithWhereUniqueWithoutVideoInput | Prisma.TranslationUpdateWithWhereUniqueWithoutVideoInput[]
  updateMany?: Prisma.TranslationUpdateManyWithWhereWithoutVideoInput | Prisma.TranslationUpdateManyWithWhereWithoutVideoInput[]
  deleteMany?: Prisma.TranslationScalarWhereInput | Prisma.TranslationScalarWhereInput[]
}

export type TranslationUncheckedUpdateManyWithoutVideoNestedInput = {
  create?: Prisma.XOR<Prisma.TranslationCreateWithoutVideoInput, Prisma.TranslationUncheckedCreateWithoutVideoInput> | Prisma.TranslationCreateWithoutVideoInput[] | Prisma.TranslationUncheckedCreateWithoutVideoInput[]
  connectOrCreate?: Prisma.TranslationCreateOrConnectWithoutVideoInput | Prisma.TranslationCreateOrConnectWithoutVideoInput[]
  upsert?: Prisma.TranslationUpsertWithWhereUniqueWithoutVideoInput | Prisma.TranslationUpsertWithWhereUniqueWithoutVideoInput[]
  createMany?: Prisma.TranslationCreateManyVideoInputEnvelope
  set?: Prisma.TranslationWhereUniqueInput | Prisma.TranslationWhereUniqueInput[]
  disconnect?: Prisma.TranslationWhereUniqueInput | Prisma.TranslationWhereUniqueInput[]
  delete?: Prisma.TranslationWhereUniqueInput | Prisma.TranslationWhereUniqueInput[]
  connect?: Prisma.TranslationWhereUniqueInput | Prisma.TranslationWhereUniqueInput[]
  update?: Prisma.TranslationUpdateWithWhereUniqueWithoutVideoInput | Prisma.TranslationUpdateWithWhereUniqueWithoutVideoInput[]
  updateMany?: Prisma.TranslationUpdateManyWithWhereWithoutVideoInput | Prisma.TranslationUpdateManyWithWhereWithoutVideoInput[]
  deleteMany?: Prisma.TranslationScalarWhereInput | Prisma.TranslationScalarWhereInput[]
}

export type EnumTranslationStatusFieldUpdateOperationsInput = {
  set?: $Enums.TranslationStatus
}

export type NullableEnumPipelineStepFieldUpdateOperationsInput = {
  set?: $Enums.PipelineStep | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type TranslationCreateWithoutVideoInput = {
  id?: string
  targetLanguage: string
  status?: $Enums.TranslationStatus
  currentStep?: $Enums.PipelineStep | null
  progress?: number
  extractedAudioKey?: string | null
  transcriptJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  synthesizedAudioKey?: string | null
  resultVideoKey?: string | null
  fishAudioVoiceId?: string | null
  fishAudioVoiceMap?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  errorMessage?: string | null
  errorStep?: $Enums.PipelineStep | null
  retryCount?: number
  startedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationUncheckedCreateWithoutVideoInput = {
  id?: string
  targetLanguage: string
  status?: $Enums.TranslationStatus
  currentStep?: $Enums.PipelineStep | null
  progress?: number
  extractedAudioKey?: string | null
  transcriptJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  synthesizedAudioKey?: string | null
  resultVideoKey?: string | null
  fishAudioVoiceId?: string | null
  fishAudioVoiceMap?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  errorMessage?: string | null
  errorStep?: $Enums.PipelineStep | null
  retryCount?: number
  startedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationCreateOrConnectWithoutVideoInput = {
  where: Prisma.TranslationWhereUniqueInput
  create: Prisma.XOR<Prisma.TranslationCreateWithoutVideoInput, Prisma.TranslationUncheckedCreateWithoutVideoInput>
}

export type TranslationCreateManyVideoInputEnvelope = {
  data: Prisma.TranslationCreateManyVideoInput | Prisma.TranslationCreateManyVideoInput[]
  skipDuplicates?: boolean
}

export type TranslationUpsertWithWhereUniqueWithoutVideoInput = {
  where: Prisma.TranslationWhereUniqueInput
  update: Prisma.XOR<Prisma.TranslationUpdateWithoutVideoInput, Prisma.TranslationUncheckedUpdateWithoutVideoInput>
  create: Prisma.XOR<Prisma.TranslationCreateWithoutVideoInput, Prisma.TranslationUncheckedCreateWithoutVideoInput>
}

export type TranslationUpdateWithWhereUniqueWithoutVideoInput = {
  where: Prisma.TranslationWhereUniqueInput
  data: Prisma.XOR<Prisma.TranslationUpdateWithoutVideoInput, Prisma.TranslationUncheckedUpdateWithoutVideoInput>
}

export type TranslationUpdateManyWithWhereWithoutVideoInput = {
  where: Prisma.TranslationScalarWhereInput
  data: Prisma.XOR<Prisma.TranslationUpdateManyMutationInput, Prisma.TranslationUncheckedUpdateManyWithoutVideoInput>
}

export type TranslationScalarWhereInput = {
  AND?: Prisma.TranslationScalarWhereInput | Prisma.TranslationScalarWhereInput[]
  OR?: Prisma.TranslationScalarWhereInput[]
  NOT?: Prisma.TranslationScalarWhereInput | Prisma.TranslationScalarWhereInput[]
  id?: Prisma.StringFilter<"Translation"> | string
  videoId?: Prisma.StringFilter<"Translation"> | string
  targetLanguage?: Prisma.StringFilter<"Translation"> | string
  status?: Prisma.EnumTranslationStatusFilter<"Translation"> | $Enums.TranslationStatus
  currentStep?: Prisma.EnumPipelineStepNullableFilter<"Translation"> | $Enums.PipelineStep | null
  progress?: Prisma.IntFilter<"Translation"> | number
  extractedAudioKey?: Prisma.StringNullableFilter<"Translation"> | string | null
  transcriptJson?: Prisma.JsonNullableFilter<"Translation">
  translatedJson?: Prisma.JsonNullableFilter<"Translation">
  synthesizedAudioKey?: Prisma.StringNullableFilter<"Translation"> | string | null
  resultVideoKey?: Prisma.StringNullableFilter<"Translation"> | string | null
  fishAudioVoiceId?: Prisma.StringNullableFilter<"Translation"> | string | null
  fishAudioVoiceMap?: Prisma.JsonNullableFilter<"Translation">
  errorMessage?: Prisma.StringNullableFilter<"Translation"> | string | null
  errorStep?: Prisma.EnumPipelineStepNullableFilter<"Translation"> | $Enums.PipelineStep | null
  retryCount?: Prisma.IntFilter<"Translation"> | number
  startedAt?: Prisma.DateTimeNullableFilter<"Translation"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableFilter<"Translation"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Translation"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Translation"> | Date | string
}

export type TranslationCreateManyVideoInput = {
  id?: string
  targetLanguage: string
  status?: $Enums.TranslationStatus
  currentStep?: $Enums.PipelineStep | null
  progress?: number
  extractedAudioKey?: string | null
  transcriptJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  synthesizedAudioKey?: string | null
  resultVideoKey?: string | null
  fishAudioVoiceId?: string | null
  fishAudioVoiceMap?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  errorMessage?: string | null
  errorStep?: $Enums.PipelineStep | null
  retryCount?: number
  startedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationUpdateWithoutVideoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTranslationStatusFieldUpdateOperationsInput | $Enums.TranslationStatus
  currentStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  extractedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transcriptJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  synthesizedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resultVideoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceMap?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  retryCount?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationUncheckedUpdateWithoutVideoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTranslationStatusFieldUpdateOperationsInput | $Enums.TranslationStatus
  currentStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  extractedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transcriptJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  synthesizedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resultVideoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceMap?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  retryCount?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationUncheckedUpdateManyWithoutVideoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTranslationStatusFieldUpdateOperationsInput | $Enums.TranslationStatus
  currentStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  extractedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transcriptJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  synthesizedAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resultVideoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fishAudioVoiceMap?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorStep?: Prisma.NullableEnumPipelineStepFieldUpdateOperationsInput | $Enums.PipelineStep | null
  retryCount?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TranslationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoId?: boolean
  targetLanguage?: boolean
  status?: boolean
  currentStep?: boolean
  progress?: boolean
  extractedAudioKey?: boolean
  transcriptJson?: boolean
  translatedJson?: boolean
  synthesizedAudioKey?: boolean
  resultVideoKey?: boolean
  fishAudioVoiceId?: boolean
  fishAudioVoiceMap?: boolean
  errorMessage?: boolean
  errorStep?: boolean
  retryCount?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  video?: boolean | Prisma.VideoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translation"]>

export type TranslationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoId?: boolean
  targetLanguage?: boolean
  status?: boolean
  currentStep?: boolean
  progress?: boolean
  extractedAudioKey?: boolean
  transcriptJson?: boolean
  translatedJson?: boolean
  synthesizedAudioKey?: boolean
  resultVideoKey?: boolean
  fishAudioVoiceId?: boolean
  fishAudioVoiceMap?: boolean
  errorMessage?: boolean
  errorStep?: boolean
  retryCount?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  video?: boolean | Prisma.VideoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translation"]>

export type TranslationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoId?: boolean
  targetLanguage?: boolean
  status?: boolean
  currentStep?: boolean
  progress?: boolean
  extractedAudioKey?: boolean
  transcriptJson?: boolean
  translatedJson?: boolean
  synthesizedAudioKey?: boolean
  resultVideoKey?: boolean
  fishAudioVoiceId?: boolean
  fishAudioVoiceMap?: boolean
  errorMessage?: boolean
  errorStep?: boolean
  retryCount?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  video?: boolean | Prisma.VideoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translation"]>

export type TranslationSelectScalar = {
  id?: boolean
  videoId?: boolean
  targetLanguage?: boolean
  status?: boolean
  currentStep?: boolean
  progress?: boolean
  extractedAudioKey?: boolean
  transcriptJson?: boolean
  translatedJson?: boolean
  synthesizedAudioKey?: boolean
  resultVideoKey?: boolean
  fishAudioVoiceId?: boolean
  fishAudioVoiceMap?: boolean
  errorMessage?: boolean
  errorStep?: boolean
  retryCount?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TranslationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "videoId" | "targetLanguage" | "status" | "currentStep" | "progress" | "extractedAudioKey" | "transcriptJson" | "translatedJson" | "synthesizedAudioKey" | "resultVideoKey" | "fishAudioVoiceId" | "fishAudioVoiceMap" | "errorMessage" | "errorStep" | "retryCount" | "startedAt" | "completedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["translation"]>
export type TranslationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  video?: boolean | Prisma.VideoDefaultArgs<ExtArgs>
}
export type TranslationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  video?: boolean | Prisma.VideoDefaultArgs<ExtArgs>
}
export type TranslationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  video?: boolean | Prisma.VideoDefaultArgs<ExtArgs>
}

export type $TranslationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Translation"
  objects: {
    video: Prisma.$VideoPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    videoId: string
    targetLanguage: string
    status: $Enums.TranslationStatus
    currentStep: $Enums.PipelineStep | null
    progress: number
    extractedAudioKey: string | null
    transcriptJson: runtime.JsonValue | null
    translatedJson: runtime.JsonValue | null
    synthesizedAudioKey: string | null
    resultVideoKey: string | null
    fishAudioVoiceId: string | null
    fishAudioVoiceMap: runtime.JsonValue | null
    errorMessage: string | null
    errorStep: $Enums.PipelineStep | null
    retryCount: number
    startedAt: Date | null
    completedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["translation"]>
  composites: {}
}

export type TranslationGetPayload<S extends boolean | null | undefined | TranslationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TranslationPayload, S>

export type TranslationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TranslationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TranslationCountAggregateInputType | true
  }

export interface TranslationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Translation'], meta: { name: 'Translation' } }
  /**
   * Find zero or one Translation that matches the filter.
   * @param {TranslationFindUniqueArgs} args - Arguments to find a Translation
   * @example
   * // Get one Translation
   * const translation = await prisma.translation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TranslationFindUniqueArgs>(args: Prisma.SelectSubset<T, TranslationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TranslationClient<runtime.Types.Result.GetResult<Prisma.$TranslationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Translation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TranslationFindUniqueOrThrowArgs} args - Arguments to find a Translation
   * @example
   * // Get one Translation
   * const translation = await prisma.translation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TranslationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TranslationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TranslationClient<runtime.Types.Result.GetResult<Prisma.$TranslationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Translation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationFindFirstArgs} args - Arguments to find a Translation
   * @example
   * // Get one Translation
   * const translation = await prisma.translation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TranslationFindFirstArgs>(args?: Prisma.SelectSubset<T, TranslationFindFirstArgs<ExtArgs>>): Prisma.Prisma__TranslationClient<runtime.Types.Result.GetResult<Prisma.$TranslationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Translation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationFindFirstOrThrowArgs} args - Arguments to find a Translation
   * @example
   * // Get one Translation
   * const translation = await prisma.translation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TranslationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TranslationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TranslationClient<runtime.Types.Result.GetResult<Prisma.$TranslationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Translations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Translations
   * const translations = await prisma.translation.findMany()
   * 
   * // Get first 10 Translations
   * const translations = await prisma.translation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const translationWithIdOnly = await prisma.translation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TranslationFindManyArgs>(args?: Prisma.SelectSubset<T, TranslationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Translation.
   * @param {TranslationCreateArgs} args - Arguments to create a Translation.
   * @example
   * // Create one Translation
   * const Translation = await prisma.translation.create({
   *   data: {
   *     // ... data to create a Translation
   *   }
   * })
   * 
   */
  create<T extends TranslationCreateArgs>(args: Prisma.SelectSubset<T, TranslationCreateArgs<ExtArgs>>): Prisma.Prisma__TranslationClient<runtime.Types.Result.GetResult<Prisma.$TranslationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Translations.
   * @param {TranslationCreateManyArgs} args - Arguments to create many Translations.
   * @example
   * // Create many Translations
   * const translation = await prisma.translation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TranslationCreateManyArgs>(args?: Prisma.SelectSubset<T, TranslationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Translations and returns the data saved in the database.
   * @param {TranslationCreateManyAndReturnArgs} args - Arguments to create many Translations.
   * @example
   * // Create many Translations
   * const translation = await prisma.translation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Translations and only return the `id`
   * const translationWithIdOnly = await prisma.translation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TranslationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TranslationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Translation.
   * @param {TranslationDeleteArgs} args - Arguments to delete one Translation.
   * @example
   * // Delete one Translation
   * const Translation = await prisma.translation.delete({
   *   where: {
   *     // ... filter to delete one Translation
   *   }
   * })
   * 
   */
  delete<T extends TranslationDeleteArgs>(args: Prisma.SelectSubset<T, TranslationDeleteArgs<ExtArgs>>): Prisma.Prisma__TranslationClient<runtime.Types.Result.GetResult<Prisma.$TranslationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Translation.
   * @param {TranslationUpdateArgs} args - Arguments to update one Translation.
   * @example
   * // Update one Translation
   * const translation = await prisma.translation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TranslationUpdateArgs>(args: Prisma.SelectSubset<T, TranslationUpdateArgs<ExtArgs>>): Prisma.Prisma__TranslationClient<runtime.Types.Result.GetResult<Prisma.$TranslationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Translations.
   * @param {TranslationDeleteManyArgs} args - Arguments to filter Translations to delete.
   * @example
   * // Delete a few Translations
   * const { count } = await prisma.translation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TranslationDeleteManyArgs>(args?: Prisma.SelectSubset<T, TranslationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Translations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Translations
   * const translation = await prisma.translation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TranslationUpdateManyArgs>(args: Prisma.SelectSubset<T, TranslationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Translations and returns the data updated in the database.
   * @param {TranslationUpdateManyAndReturnArgs} args - Arguments to update many Translations.
   * @example
   * // Update many Translations
   * const translation = await prisma.translation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Translations and only return the `id`
   * const translationWithIdOnly = await prisma.translation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TranslationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TranslationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Translation.
   * @param {TranslationUpsertArgs} args - Arguments to update or create a Translation.
   * @example
   * // Update or create a Translation
   * const translation = await prisma.translation.upsert({
   *   create: {
   *     // ... data to create a Translation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Translation we want to update
   *   }
   * })
   */
  upsert<T extends TranslationUpsertArgs>(args: Prisma.SelectSubset<T, TranslationUpsertArgs<ExtArgs>>): Prisma.Prisma__TranslationClient<runtime.Types.Result.GetResult<Prisma.$TranslationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Translations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationCountArgs} args - Arguments to filter Translations to count.
   * @example
   * // Count the number of Translations
   * const count = await prisma.translation.count({
   *   where: {
   *     // ... the filter for the Translations we want to count
   *   }
   * })
  **/
  count<T extends TranslationCountArgs>(
    args?: Prisma.Subset<T, TranslationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TranslationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Translation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TranslationAggregateArgs>(args: Prisma.Subset<T, TranslationAggregateArgs>): Prisma.PrismaPromise<GetTranslationAggregateType<T>>

  /**
   * Group by Translation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TranslationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TranslationGroupByArgs['orderBy'] }
      : { orderBy?: TranslationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TranslationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTranslationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Translation model
 */
readonly fields: TranslationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Translation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TranslationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  video<T extends Prisma.VideoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VideoDefaultArgs<ExtArgs>>): Prisma.Prisma__VideoClient<runtime.Types.Result.GetResult<Prisma.$VideoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Translation model
 */
export interface TranslationFieldRefs {
  readonly id: Prisma.FieldRef<"Translation", 'String'>
  readonly videoId: Prisma.FieldRef<"Translation", 'String'>
  readonly targetLanguage: Prisma.FieldRef<"Translation", 'String'>
  readonly status: Prisma.FieldRef<"Translation", 'TranslationStatus'>
  readonly currentStep: Prisma.FieldRef<"Translation", 'PipelineStep'>
  readonly progress: Prisma.FieldRef<"Translation", 'Int'>
  readonly extractedAudioKey: Prisma.FieldRef<"Translation", 'String'>
  readonly transcriptJson: Prisma.FieldRef<"Translation", 'Json'>
  readonly translatedJson: Prisma.FieldRef<"Translation", 'Json'>
  readonly synthesizedAudioKey: Prisma.FieldRef<"Translation", 'String'>
  readonly resultVideoKey: Prisma.FieldRef<"Translation", 'String'>
  readonly fishAudioVoiceId: Prisma.FieldRef<"Translation", 'String'>
  readonly fishAudioVoiceMap: Prisma.FieldRef<"Translation", 'Json'>
  readonly errorMessage: Prisma.FieldRef<"Translation", 'String'>
  readonly errorStep: Prisma.FieldRef<"Translation", 'PipelineStep'>
  readonly retryCount: Prisma.FieldRef<"Translation", 'Int'>
  readonly startedAt: Prisma.FieldRef<"Translation", 'DateTime'>
  readonly completedAt: Prisma.FieldRef<"Translation", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Translation", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Translation", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Translation findUnique
 */
export type TranslationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Translation
   */
  select?: Prisma.TranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Translation
   */
  omit?: Prisma.TranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInclude<ExtArgs> | null
  /**
   * Filter, which Translation to fetch.
   */
  where: Prisma.TranslationWhereUniqueInput
}

/**
 * Translation findUniqueOrThrow
 */
export type TranslationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Translation
   */
  select?: Prisma.TranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Translation
   */
  omit?: Prisma.TranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInclude<ExtArgs> | null
  /**
   * Filter, which Translation to fetch.
   */
  where: Prisma.TranslationWhereUniqueInput
}

/**
 * Translation findFirst
 */
export type TranslationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Translation
   */
  select?: Prisma.TranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Translation
   */
  omit?: Prisma.TranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInclude<ExtArgs> | null
  /**
   * Filter, which Translation to fetch.
   */
  where?: Prisma.TranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Translations to fetch.
   */
  orderBy?: Prisma.TranslationOrderByWithRelationInput | Prisma.TranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Translations.
   */
  cursor?: Prisma.TranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Translations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Translations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Translations.
   */
  distinct?: Prisma.TranslationScalarFieldEnum | Prisma.TranslationScalarFieldEnum[]
}

/**
 * Translation findFirstOrThrow
 */
export type TranslationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Translation
   */
  select?: Prisma.TranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Translation
   */
  omit?: Prisma.TranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInclude<ExtArgs> | null
  /**
   * Filter, which Translation to fetch.
   */
  where?: Prisma.TranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Translations to fetch.
   */
  orderBy?: Prisma.TranslationOrderByWithRelationInput | Prisma.TranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Translations.
   */
  cursor?: Prisma.TranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Translations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Translations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Translations.
   */
  distinct?: Prisma.TranslationScalarFieldEnum | Prisma.TranslationScalarFieldEnum[]
}

/**
 * Translation findMany
 */
export type TranslationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Translation
   */
  select?: Prisma.TranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Translation
   */
  omit?: Prisma.TranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInclude<ExtArgs> | null
  /**
   * Filter, which Translations to fetch.
   */
  where?: Prisma.TranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Translations to fetch.
   */
  orderBy?: Prisma.TranslationOrderByWithRelationInput | Prisma.TranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Translations.
   */
  cursor?: Prisma.TranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Translations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Translations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Translations.
   */
  distinct?: Prisma.TranslationScalarFieldEnum | Prisma.TranslationScalarFieldEnum[]
}

/**
 * Translation create
 */
export type TranslationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Translation
   */
  select?: Prisma.TranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Translation
   */
  omit?: Prisma.TranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInclude<ExtArgs> | null
  /**
   * The data needed to create a Translation.
   */
  data: Prisma.XOR<Prisma.TranslationCreateInput, Prisma.TranslationUncheckedCreateInput>
}

/**
 * Translation createMany
 */
export type TranslationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Translations.
   */
  data: Prisma.TranslationCreateManyInput | Prisma.TranslationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Translation createManyAndReturn
 */
export type TranslationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Translation
   */
  select?: Prisma.TranslationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Translation
   */
  omit?: Prisma.TranslationOmit<ExtArgs> | null
  /**
   * The data used to create many Translations.
   */
  data: Prisma.TranslationCreateManyInput | Prisma.TranslationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Translation update
 */
export type TranslationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Translation
   */
  select?: Prisma.TranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Translation
   */
  omit?: Prisma.TranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInclude<ExtArgs> | null
  /**
   * The data needed to update a Translation.
   */
  data: Prisma.XOR<Prisma.TranslationUpdateInput, Prisma.TranslationUncheckedUpdateInput>
  /**
   * Choose, which Translation to update.
   */
  where: Prisma.TranslationWhereUniqueInput
}

/**
 * Translation updateMany
 */
export type TranslationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Translations.
   */
  data: Prisma.XOR<Prisma.TranslationUpdateManyMutationInput, Prisma.TranslationUncheckedUpdateManyInput>
  /**
   * Filter which Translations to update
   */
  where?: Prisma.TranslationWhereInput
  /**
   * Limit how many Translations to update.
   */
  limit?: number
}

/**
 * Translation updateManyAndReturn
 */
export type TranslationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Translation
   */
  select?: Prisma.TranslationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Translation
   */
  omit?: Prisma.TranslationOmit<ExtArgs> | null
  /**
   * The data used to update Translations.
   */
  data: Prisma.XOR<Prisma.TranslationUpdateManyMutationInput, Prisma.TranslationUncheckedUpdateManyInput>
  /**
   * Filter which Translations to update
   */
  where?: Prisma.TranslationWhereInput
  /**
   * Limit how many Translations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Translation upsert
 */
export type TranslationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Translation
   */
  select?: Prisma.TranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Translation
   */
  omit?: Prisma.TranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInclude<ExtArgs> | null
  /**
   * The filter to search for the Translation to update in case it exists.
   */
  where: Prisma.TranslationWhereUniqueInput
  /**
   * In case the Translation found by the `where` argument doesn't exist, create a new Translation with this data.
   */
  create: Prisma.XOR<Prisma.TranslationCreateInput, Prisma.TranslationUncheckedCreateInput>
  /**
   * In case the Translation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TranslationUpdateInput, Prisma.TranslationUncheckedUpdateInput>
}

/**
 * Translation delete
 */
export type TranslationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Translation
   */
  select?: Prisma.TranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Translation
   */
  omit?: Prisma.TranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInclude<ExtArgs> | null
  /**
   * Filter which Translation to delete.
   */
  where: Prisma.TranslationWhereUniqueInput
}

/**
 * Translation deleteMany
 */
export type TranslationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Translations to delete
   */
  where?: Prisma.TranslationWhereInput
  /**
   * Limit how many Translations to delete.
   */
  limit?: number
}

/**
 * Translation without action
 */
export type TranslationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Translation
   */
  select?: Prisma.TranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Translation
   */
  omit?: Prisma.TranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInclude<ExtArgs> | null
}
