
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  USER: 'USER',
  ADMIN: 'ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const SourceType = {
  UPLOAD: 'UPLOAD',
  YOUTUBE: 'YOUTUBE',
  INSTAGRAM: 'INSTAGRAM',
  FACEBOOK: 'FACEBOOK',
  VIMEO: 'VIMEO'
} as const

export type SourceType = (typeof SourceType)[keyof typeof SourceType]


export const TranslationStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
} as const

export type TranslationStatus = (typeof TranslationStatus)[keyof typeof TranslationStatus]


export const PipelineStep = {
  DOWNLOAD: 'DOWNLOAD',
  EXTRACT_AUDIO: 'EXTRACT_AUDIO',
  TRANSCRIBE: 'TRANSCRIBE',
  TRANSLATE: 'TRANSLATE',
  CLONE_VOICE: 'CLONE_VOICE',
  SYNTHESIZE: 'SYNTHESIZE',
  MERGE: 'MERGE'
} as const

export type PipelineStep = (typeof PipelineStep)[keyof typeof PipelineStep]
